---
- name: CONTENT
  hosts: centos_slave
  tasks:
    
    - name: CREATE DIR LOCATIONS
      file:
        path: /etc/nginx/conf.d/locations
        state: directory
        owner: nginx
        group: nginx
        mode: '0755'

    - name: CREATE DIR UPSTREAMS
      file:
        path: /etc/nginx/conf.d/upstreams
        state: directory
        owner: nginx
        group: nginx
        mode: '0755'
        

    - name: DELETE DEFAULT NGINX.CONF
      file:
        path: /etc/nginx/nginx.conf
        state: absent

    - name: COPY NGINX FILES
      copy:
        src: /ansible/ansible_automation/nginx_files/nginx.conf
        dest: /etc/nginx/nginx.conf 
        owner: nginx
        group: nginx
        mode: '0755'

    - name: COPY LOCATIONS
      copy:
        src: /ansible/ansible_automation/nginx_files/locations.conf
        dest: /etc/nginx/conf.d/locations/locations.conf
        owner: nginx
        group: nginx
        mode: '0755'

    - name: RELOAD NGINX
      systemd:
        name: nginx
        state: restarted
...
