---
- name: INSTALL NGINX
  hosts: centos_slave
  tasks:
    
    - name: INSTALL NGINX
      yum:
        name: nginx
        state: latest

    - name: START NGINX
      systemd:
        name: nginx
        state: started
        enabled: true    

    - name: ALLOW ACCESS TO WEB SERVER
      firewalld:
        port: 9080/tcp
        state: enabled
        immediate: yes
        permanent: yes

    - name: DELETE DEFAULT NGINX.CONF
      file:
        path: /etc/nginx/nginx.conf
        state: absent

- import_playbook: nginx_content.yml
...
